server.port=${PORT:8080}
server.tomcat.relaxed-query-chars=[,]
spring.jpa.hibernate.ddl-auto=update
google.cloud.storage.bucket=${GCP_STORAGE_BUCKET:myb-lobby}
google.cloud.credentials.path=${GCP_CREDENTIALS_PATH:}
brevo.api.key=${BREVO_API_KEY:}
brevo.email.from=${BREVO_EMAIL_FROM:no-reply@fabbuilder.com}
spring.data.mongodb.repositories.enabled=true
spring.data.mongodb.auditing.enabled=true
spring.config.import=optional:classpath:application-local.properties

# SpringDoc OpenAPI / Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.default-models-expand-depth=1
springdoc.swagger-ui.default-model-expand-depth=1
springdoc.swagger-ui.show-extensions=false
springdoc.swagger-ui.show-common-extensions=false
