server.port=${PORT:8080}
server.tomcat.relaxed-query-chars=[,]
spring.jpa.hibernate.ddl-auto=update
google.cloud.storage.bucket=${GCP_STORAGE_BUCKET:myb-lobby}
google.cloud.credentials.path=${GCP_CREDENTIALS_PATH:}
brevo.api.key=${BREVO_API_KEY:}
brevo.email.from=${BREVO_EMAIL_FROM:no-reply@fabbuilder.com}
spring.data.mongodb.repositories.enabled=true
spring.data.mongodb.auditing.enabled=true
spring.config.import=optional:classpath:application-local.properties


